package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Asiento generated by hbm2java
 */
public class Asiento  implements java.io.Serializable {


     private Integer id;
     private Ejercicio ejercicio;
     private Plantilla plantilla;
     private Date fecMov;
     private Date fecCarga;
     private int idUsuario;
     private String descripcion;
     private Set<AsientoDet> asientoDets = new HashSet<AsientoDet>(0);
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);

    public Asiento() {
    }

	
    public Asiento(Ejercicio ejercicio, Date fecMov, Date fecCarga, int idUsuario) {
        this.ejercicio = ejercicio;
        this.fecMov = fecMov;
        this.fecCarga = fecCarga;
        this.idUsuario = idUsuario;
    }
    public Asiento(Ejercicio ejercicio, Plantilla plantilla, Date fecMov, Date fecCarga, int idUsuario, String descripcion, Set<AsientoDet> asientoDets, Set<Solicitud> solicituds) {
       this.ejercicio = ejercicio;
       this.plantilla = plantilla;
       this.fecMov = fecMov;
       this.fecCarga = fecCarga;
       this.idUsuario = idUsuario;
       this.descripcion = descripcion;
       this.asientoDets = asientoDets;
       this.solicituds = solicituds;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Ejercicio getEjercicio() {
        return this.ejercicio;
    }
    
    public void setEjercicio(Ejercicio ejercicio) {
        this.ejercicio = ejercicio;
    }
    public Plantilla getPlantilla() {
        return this.plantilla;
    }
    
    public void setPlantilla(Plantilla plantilla) {
        this.plantilla = plantilla;
    }
    public Date getFecMov() {
        return this.fecMov;
    }
    
    public void setFecMov(Date fecMov) {
        this.fecMov = fecMov;
    }
    public Date getFecCarga() {
        return this.fecCarga;
    }
    
    public void setFecCarga(Date fecCarga) {
        this.fecCarga = fecCarga;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<AsientoDet> getAsientoDets() {
        return this.asientoDets;
    }
    
    public void setAsientoDets(Set<AsientoDet> asientoDets) {
        this.asientoDets = asientoDets;
    }
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }




}


