package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Banco generated by hbm2java
 */
public class Banco  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<CarteraCheques> carteraChequeses = new HashSet<CarteraCheques>(0);
     private Set<CuentaFondos> cuentaFondoses = new HashSet<CuentaFondos>(0);

    public Banco() {
    }

	
    public Banco(String nombre) {
        this.nombre = nombre;
    }
    public Banco(String nombre, Set<CarteraCheques> carteraChequeses, Set<CuentaFondos> cuentaFondoses) {
       this.nombre = nombre;
       this.carteraChequeses = carteraChequeses;
       this.cuentaFondoses = cuentaFondoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<CarteraCheques> getCarteraChequeses() {
        return this.carteraChequeses;
    }
    
    public void setCarteraChequeses(Set<CarteraCheques> carteraChequeses) {
        this.carteraChequeses = carteraChequeses;
    }
    public Set<CuentaFondos> getCuentaFondoses() {
        return this.cuentaFondoses;
    }
    
    public void setCuentaFondoses(Set<CuentaFondos> cuentaFondoses) {
        this.cuentaFondoses = cuentaFondoses;
    }




}


