package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CarteraCheques generated by hbm2java
 */
public class CarteraCheques  implements java.io.Serializable {


     private Integer id;
     private Banco banco;
     private CuentaFondos cuentaFondos;
     private String numCheque;
     private char tipoCheque;
     private Date vencCheque;
     private BigDecimal valor;
     private char estado;

    public CarteraCheques() {
    }

    public CarteraCheques(Banco banco, CuentaFondos cuentaFondos, String numCheque, char tipoCheque, Date vencCheque, BigDecimal valor, char estado) {
       this.banco = banco;
       this.cuentaFondos = cuentaFondos;
       this.numCheque = numCheque;
       this.tipoCheque = tipoCheque;
       this.vencCheque = vencCheque;
       this.valor = valor;
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Banco getBanco() {
        return this.banco;
    }
    
    public void setBanco(Banco banco) {
        this.banco = banco;
    }
    public CuentaFondos getCuentaFondos() {
        return this.cuentaFondos;
    }
    
    public void setCuentaFondos(CuentaFondos cuentaFondos) {
        this.cuentaFondos = cuentaFondos;
    }
    public String getNumCheque() {
        return this.numCheque;
    }
    
    public void setNumCheque(String numCheque) {
        this.numCheque = numCheque;
    }
    public char getTipoCheque() {
        return this.tipoCheque;
    }
    
    public void setTipoCheque(char tipoCheque) {
        this.tipoCheque = tipoCheque;
    }
    public Date getVencCheque() {
        return this.vencCheque;
    }
    
    public void setVencCheque(Date vencCheque) {
        this.vencCheque = vencCheque;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }




}


