package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CategoriaRetencion generated by hbm2java
 */
public class CategoriaRetencion  implements java.io.Serializable {


     private Integer id;
     private Empresa empresa;
     private String nombre;
     private Set<SubcategoriaRetencion> subcategoriaRetencions = new HashSet<SubcategoriaRetencion>(0);

    public CategoriaRetencion() {
    }

	
    public CategoriaRetencion(Empresa empresa, String nombre) {
        this.empresa = empresa;
        this.nombre = nombre;
    }
    public CategoriaRetencion(Empresa empresa, String nombre, Set<SubcategoriaRetencion> subcategoriaRetencions) {
       this.empresa = empresa;
       this.nombre = nombre;
       this.subcategoriaRetencions = subcategoriaRetencions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<SubcategoriaRetencion> getSubcategoriaRetencions() {
        return this.subcategoriaRetencions;
    }
    
    public void setSubcategoriaRetencions(Set<SubcategoriaRetencion> subcategoriaRetencions) {
        this.subcategoriaRetencions = subcategoriaRetencions;
    }




}


