package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CategoriaPercepcion generated by hbm2java
 */
public class CategoriaPercepcion  implements java.io.Serializable {


     private Integer id;
     private Empresa empresa;
     private String nombre;
     private Set<SubcategoriaPercepcion> subcategoriaPercepcions = new HashSet<SubcategoriaPercepcion>(0);

    public CategoriaPercepcion() {
    }

	
    public CategoriaPercepcion(Empresa empresa, String nombre) {
        this.empresa = empresa;
        this.nombre = nombre;
    }
    public CategoriaPercepcion(Empresa empresa, String nombre, Set<SubcategoriaPercepcion> subcategoriaPercepcions) {
       this.empresa = empresa;
       this.nombre = nombre;
       this.subcategoriaPercepcions = subcategoriaPercepcions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<SubcategoriaPercepcion> getSubcategoriaPercepcions() {
        return this.subcategoriaPercepcions;
    }
    
    public void setSubcategoriaPercepcions(Set<SubcategoriaPercepcion> subcategoriaPercepcions) {
        this.subcategoriaPercepcions = subcategoriaPercepcions;
    }




}


