package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CentroCosto generated by hbm2java
 */
public class CentroCosto  implements java.io.Serializable {


     private Integer id;
     private Ejercicio ejercicio;
     private String nombre;
     private String abrev;
     private Set<AsientoDet> asientoDets = new HashSet<AsientoDet>(0);

    public CentroCosto() {
    }

	
    public CentroCosto(Ejercicio ejercicio, String nombre, String abrev) {
        this.ejercicio = ejercicio;
        this.nombre = nombre;
        this.abrev = abrev;
    }
    public CentroCosto(Ejercicio ejercicio, String nombre, String abrev, Set<AsientoDet> asientoDets) {
       this.ejercicio = ejercicio;
       this.nombre = nombre;
       this.abrev = abrev;
       this.asientoDets = asientoDets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Ejercicio getEjercicio() {
        return this.ejercicio;
    }
    
    public void setEjercicio(Ejercicio ejercicio) {
        this.ejercicio = ejercicio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAbrev() {
        return this.abrev;
    }
    
    public void setAbrev(String abrev) {
        this.abrev = abrev;
    }
    public Set<AsientoDet> getAsientoDets() {
        return this.asientoDets;
    }
    
    public void setAsientoDets(Set<AsientoDet> asientoDets) {
        this.asientoDets = asientoDets;
    }




}


