package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * CuentaFondos generated by hbm2java
 */

public class CuentaFondos  implements java.io.Serializable {
     private Integer id;
     private Banco banco;
     private Empresa empresa;
     private Moneda moneda= new Moneda();
     private char tipoCuenta;
     private String nombreCuenta;
     private String numeroCuenta;
     private String cuentaContablePagos;
     private Integer numPlantillaEfec;
     private Integer numPlantillaCheques;
     private Set<CarteraCheques> carteraChequeses = new HashSet<CarteraCheques>(0);
     private Set<Recibo> recibos = new HashSet<Recibo>(0);
     private Set<MovCuenta> movCuentas = new HashSet<MovCuenta>(0);

    public CuentaFondos() {
    }

	
    public CuentaFondos(Empresa empresa, Moneda moneda, char tipoCuenta) {
        this.empresa = empresa;
        this.moneda = moneda;
        this.tipoCuenta = tipoCuenta;
    }
    public CuentaFondos(Banco banco, Empresa empresa, Moneda moneda, char tipoCuenta, String nombreCuenta, String numeroCuenta, String cuentaContablePagos, Integer numPlantillaEfec, Integer numPlantillaCheques, Set<CarteraCheques> carteraChequeses, Set<Recibo> recibos, Set<MovCuenta> movCuentas) {
       this.banco = banco;
       this.empresa = empresa;
       this.moneda = moneda;
       this.tipoCuenta = tipoCuenta;
       this.nombreCuenta = nombreCuenta;
       this.numeroCuenta = numeroCuenta;
       this.cuentaContablePagos = cuentaContablePagos;
       this.numPlantillaEfec = numPlantillaEfec;
       this.numPlantillaCheques = numPlantillaCheques;
       this.carteraChequeses = carteraChequeses;
       this.recibos = recibos;
       this.movCuentas = movCuentas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Banco getBanco() {
        return this.banco;
    }
    
    public void setBanco(Banco banco) {
        this.banco = banco;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Moneda getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(Moneda moneda) {
        this.moneda = moneda;
    }
    public char getTipoCuenta() {
        return this.tipoCuenta;
    }
    
    public void setTipoCuenta(char tipoCuenta) {
        this.tipoCuenta = tipoCuenta;
    }
    public String getNombreCuenta() {
        return this.nombreCuenta;
    }
    
    public void setNombreCuenta(String nombreCuenta) {
        this.nombreCuenta = nombreCuenta;
    }
    public String getNumeroCuenta() {
        return this.numeroCuenta;
    }
    
    public void setNumeroCuenta(String numeroCuenta) {
        this.numeroCuenta = numeroCuenta;
    }
    public String getCuentaContablePagos() {
        return this.cuentaContablePagos;
    }
    
    public void setCuentaContablePagos(String cuentaContablePagos) {
        this.cuentaContablePagos = cuentaContablePagos;
    }
    public Integer getNumPlantillaEfec() {
        return this.numPlantillaEfec;
    }
    
    public void setNumPlantillaEfec(Integer numPlantillaEfec) {
        this.numPlantillaEfec = numPlantillaEfec;
    }
    public Integer getNumPlantillaCheques() {
        return this.numPlantillaCheques;
    }
    
    public void setNumPlantillaCheques(Integer numPlantillaCheques) {
        this.numPlantillaCheques = numPlantillaCheques;
    }
    public Set<CarteraCheques> getCarteraChequeses() {
        return this.carteraChequeses;
    }
    
    public void setCarteraChequeses(Set<CarteraCheques> carteraChequeses) {
        this.carteraChequeses = carteraChequeses;
    }
    public Set<Recibo> getRecibos() {
        return this.recibos;
    }
    
    public void setRecibos(Set<Recibo> recibos) {
        this.recibos = recibos;
    }
    public Set<MovCuenta> getMovCuentas() {
        return this.movCuentas;
    }
    
    public void setMovCuentas(Set<MovCuenta> movCuentas) {
        this.movCuentas = movCuentas;
    }




}


