package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FormaPago generated by hbm2java
 */
public class FormaPago  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<Recibo> recibos = new HashSet<Recibo>(0);
     private Set<MovCuentaDet> movCuentaDets = new HashSet<MovCuentaDet>(0);

    public FormaPago() {
    }

	
    public FormaPago(String nombre) {
        this.nombre = nombre;
    }
    public FormaPago(String nombre, Set<Recibo> recibos, Set<MovCuentaDet> movCuentaDets) {
       this.nombre = nombre;
       this.recibos = recibos;
       this.movCuentaDets = movCuentaDets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Recibo> getRecibos() {
        return this.recibos;
    }
    
    public void setRecibos(Set<Recibo> recibos) {
        this.recibos = recibos;
    }
    public Set<MovCuentaDet> getMovCuentaDets() {
        return this.movCuentaDets;
    }
    
    public void setMovCuentaDets(Set<MovCuentaDet> movCuentaDets) {
        this.movCuentaDets = movCuentaDets;
    }




}


