package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * IndiceInflacion generated by hbm2java
 */
public class IndiceInflacion  implements java.io.Serializable {


     private Integer id;
     private Periodo periodo;
     private BigDecimal valorIndice;

    public IndiceInflacion() {
    }

    public IndiceInflacion(Periodo periodo, BigDecimal valorIndice) {
       this.periodo = periodo;
       this.valorIndice = valorIndice;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Periodo getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Periodo periodo) {
        this.periodo = periodo;
    }
    public BigDecimal getValorIndice() {
        return this.valorIndice;
    }
    
    public void setValorIndice(BigDecimal valorIndice) {
        this.valorIndice = valorIndice;
    }




}


