package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Iva generated by hbm2java
 */
public class Iva  implements java.io.Serializable {


     private Integer id;
     private Cuenta cuenta;
     private Empresa empresa;
     private String nombre;
     private BigDecimal porcentaje;
     private Set<SolicitudIva> solicitudIvas = new HashSet<SolicitudIva>(0);

    public Iva() {
    }

	
    public Iva(Empresa empresa, String nombre, BigDecimal porcentaje) {
        this.empresa = empresa;
        this.nombre = nombre;
        this.porcentaje = porcentaje;
    }
    public Iva(Cuenta cuenta, Empresa empresa, String nombre, BigDecimal porcentaje, Set<SolicitudIva> solicitudIvas) {
       this.cuenta = cuenta;
       this.empresa = empresa;
       this.nombre = nombre;
       this.porcentaje = porcentaje;
       this.solicitudIvas = solicitudIvas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(BigDecimal porcentaje) {
        this.porcentaje = porcentaje;
    }
    public Set<SolicitudIva> getSolicitudIvas() {
        return this.solicitudIvas;
    }
    
    public void setSolicitudIvas(Set<SolicitudIva> solicitudIvas) {
        this.solicitudIvas = solicitudIvas;
    }




}


