package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * MovCuentaRet generated by hbm2java
 */
public class MovCuentaRet  implements java.io.Serializable {


     private Integer id;
     private MovCuenta movCuenta;
     private SubcategoriaRetencion subcategoriaRetencion;
     private BigDecimal valor;

    public MovCuentaRet() {
    }

    public MovCuentaRet(MovCuenta movCuenta, SubcategoriaRetencion subcategoriaRetencion, BigDecimal valor) {
       this.movCuenta = movCuenta;
       this.subcategoriaRetencion = subcategoriaRetencion;
       this.valor = valor;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public MovCuenta getMovCuenta() {
        return this.movCuenta;
    }
    
    public void setMovCuenta(MovCuenta movCuenta) {
        this.movCuenta = movCuenta;
    }
    public SubcategoriaRetencion getSubcategoriaRetencion() {
        return this.subcategoriaRetencion;
    }
    
    public void setSubcategoriaRetencion(SubcategoriaRetencion subcategoriaRetencion) {
        this.subcategoriaRetencion = subcategoriaRetencion;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


