package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MovCuenta generated by hbm2java
 */
public class MovCuenta  implements java.io.Serializable {
     private Integer id;
     private Concepto concepto= new Concepto();
     private CuentaFondos cuentaFondos= new CuentaFondos();
     private Plantilla plantilla= new Plantilla();
     private char tipoMov;
     private char dc;
     private Date fecMov;
     private Date fecCarga;
     private int idUsuario;
     private Integer idPersona;
     private int idMoneda;
     private BigDecimal tipoCambio;
     private BigDecimal valorOriginal;
     private BigDecimal valor;
     private Integer idAsiento;
     private String observaciones;
     private Set<MovCuentaRet> movCuentaRets = new HashSet<MovCuentaRet>(0);
     private Set<MovCuentaDet> movCuentaDets = new HashSet<MovCuentaDet>(0);

    public MovCuenta() {
    }

	
    public MovCuenta(Concepto concepto, CuentaFondos cuentaFondos, Plantilla plantilla, char tipoMov, char dc, Date fecMov, Date fecCarga, int idUsuario, int idMoneda, BigDecimal tipoCambio, BigDecimal valorOriginal, BigDecimal valor) {
        this.concepto = concepto;
        this.cuentaFondos = cuentaFondos;
        this.plantilla = plantilla;
        this.tipoMov = tipoMov;
        this.dc = dc;
        this.fecMov = fecMov;
        this.fecCarga = fecCarga;
        this.idUsuario = idUsuario;
        this.idMoneda = idMoneda;
        this.tipoCambio = tipoCambio;
        this.valorOriginal = valorOriginal;
        this.valor = valor;
    }
    public MovCuenta(Concepto concepto, CuentaFondos cuentaFondos, Plantilla plantilla, char tipoMov, char dc, Date fecMov, Date fecCarga, int idUsuario, Integer idPersona, int idMoneda, BigDecimal tipoCambio, BigDecimal valorOriginal, BigDecimal valor, Integer idAsiento, String observaciones, Set<MovCuentaRet> movCuentaRets, Set<MovCuentaDet> movCuentaDets) {
       this.concepto = concepto;
       this.cuentaFondos = cuentaFondos;
       this.plantilla = plantilla;
       this.tipoMov = tipoMov;
       this.dc = dc;
       this.fecMov = fecMov;
       this.fecCarga = fecCarga;
       this.idUsuario = idUsuario;
       this.idPersona = idPersona;
       this.idMoneda = idMoneda;
       this.tipoCambio = tipoCambio;
       this.valorOriginal = valorOriginal;
       this.valor = valor;
       this.idAsiento = idAsiento;
       this.observaciones = observaciones;
       this.movCuentaRets = movCuentaRets;
       this.movCuentaDets = movCuentaDets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Concepto getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(Concepto concepto) {
        this.concepto = concepto;
    }
    public CuentaFondos getCuentaFondos() {
        return this.cuentaFondos;
    }
    
    public void setCuentaFondos(CuentaFondos cuentaFondos) {
        this.cuentaFondos = cuentaFondos;
    }
    public Plantilla getPlantilla() {
        return this.plantilla;
    }
    
    public void setPlantilla(Plantilla plantilla) {
        this.plantilla = plantilla;
    }
    public char getTipoMov() {
        return this.tipoMov;
    }
    
    public void setTipoMov(char tipoMov) {
        this.tipoMov = tipoMov;
    }
    public char getDc() {
        return this.dc;
    }
    
    public void setDc(char dc) {
        this.dc = dc;
    }
    public Date getFecMov() {
        return this.fecMov;
    }
    
    public void setFecMov(Date fecMov) {
        this.fecMov = fecMov;
    }
    public Date getFecCarga() {
        return this.fecCarga;
    }
    
    public void setFecCarga(Date fecCarga) {
        this.fecCarga = fecCarga;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
    public int getIdMoneda() {
        return this.idMoneda;
    }
    
    public void setIdMoneda(int idMoneda) {
        this.idMoneda = idMoneda;
    }
    public BigDecimal getTipoCambio() {
        return this.tipoCambio;
    }
    
    public void setTipoCambio(BigDecimal tipoCambio) {
        this.tipoCambio = tipoCambio;
    }
    public BigDecimal getValorOriginal() {
        return this.valorOriginal;
    }
    
    public void setValorOriginal(BigDecimal valorOriginal) {
        this.valorOriginal = valorOriginal;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public Integer getIdAsiento() {
        return this.idAsiento;
    }
    
    public void setIdAsiento(Integer idAsiento) {
        this.idAsiento = idAsiento;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set<MovCuentaRet> getMovCuentaRets() {
        return this.movCuentaRets;
    }
    
    public void setMovCuentaRets(Set<MovCuentaRet> movCuentaRets) {
        this.movCuentaRets = movCuentaRets;
    }
    public Set<MovCuentaDet> getMovCuentaDets() {
        return this.movCuentaDets;
    }
    
    public void setMovCuentaDets(Set<MovCuentaDet> movCuentaDets) {
        this.movCuentaDets = movCuentaDets;
    }

}


