package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * MovPeriodo generated by hbm2java
 */
public class MovPeriodo  implements java.io.Serializable {


     private Integer id;
     private Cuenta cuenta;
     private Periodo periodo;
     private BigDecimal movDebe;
     private BigDecimal movHaber;

    public MovPeriodo() {
    }

    public MovPeriodo(Cuenta cuenta, Periodo periodo, BigDecimal movDebe, BigDecimal movHaber) {
       this.cuenta = cuenta;
       this.periodo = periodo;
       this.movDebe = movDebe;
       this.movHaber = movHaber;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }
    public Periodo getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Periodo periodo) {
        this.periodo = periodo;
    }
    public BigDecimal getMovDebe() {
        return this.movDebe;
    }
    
    public void setMovDebe(BigDecimal movDebe) {
        this.movDebe = movDebe;
    }
    public BigDecimal getMovHaber() {
        return this.movHaber;
    }
    
    public void setMovHaber(BigDecimal movHaber) {
        this.movHaber = movHaber;
    }




}


