package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Periodo generated by hbm2java
 */
public class Periodo  implements java.io.Serializable {


     private Integer id;
     private Ejercicio ejercicio;
     private short anio;
     private short mes;
     private char estado;
     private char inicial;
     private Set<MovPeriodo> movPeriodos = new HashSet<MovPeriodo>(0);
     private Set<IndiceInflacion> indiceInflacions = new HashSet<IndiceInflacion>(0);

    public Periodo() {
    }

	
    public Periodo(Ejercicio ejercicio, short anio, short mes, char estado, char inicial) {
        this.ejercicio = ejercicio;
        this.anio = anio;
        this.mes = mes;
        this.estado = estado;
        this.inicial = inicial;
    }
    public Periodo(Ejercicio ejercicio, short anio, short mes, char estado, char inicial, Set<MovPeriodo> movPeriodos, Set<IndiceInflacion> indiceInflacions) {
       this.ejercicio = ejercicio;
       this.anio = anio;
       this.mes = mes;
       this.estado = estado;
       this.inicial = inicial;
       this.movPeriodos = movPeriodos;
       this.indiceInflacions = indiceInflacions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Ejercicio getEjercicio() {
        return this.ejercicio;
    }
    
    public void setEjercicio(Ejercicio ejercicio) {
        this.ejercicio = ejercicio;
    }
    public short getAnio() {
        return this.anio;
    }
    
    public void setAnio(short anio) {
        this.anio = anio;
    }
    public short getMes() {
        return this.mes;
    }
    
    public void setMes(short mes) {
        this.mes = mes;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public char getInicial() {
        return this.inicial;
    }
    
    public void setInicial(char inicial) {
        this.inicial = inicial;
    }
    public Set<MovPeriodo> getMovPeriodos() {
        return this.movPeriodos;
    }
    
    public void setMovPeriodos(Set<MovPeriodo> movPeriodos) {
        this.movPeriodos = movPeriodos;
    }
    public Set<IndiceInflacion> getIndiceInflacions() {
        return this.indiceInflacions;
    }
    
    public void setIndiceInflacions(Set<IndiceInflacion> indiceInflacions) {
        this.indiceInflacions = indiceInflacions;
    }




}


