package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Plantilla generated by hbm2java
 */
public class Plantilla  implements java.io.Serializable {


     private Integer id;
     private Ejercicio ejercicio;
     private int numero;
     private String nombre;
     private Set<Solicitud> solicituds = new HashSet<Solicitud>(0);
     private Set<MovCuenta> movCuentas = new HashSet<MovCuenta>(0);
     private Set<PlantillaParam> plantillaParams = new HashSet<PlantillaParam>(0);
     private Set<PlantillaDet> plantillaDets = new HashSet<PlantillaDet>(0);
     private Set<Asiento> asientos = new HashSet<Asiento>(0);

    public Plantilla() {
    }

	
    public Plantilla(Ejercicio ejercicio, int numero, String nombre) {
        this.ejercicio = ejercicio;
        this.numero = numero;
        this.nombre = nombre;
    }
    public Plantilla(Ejercicio ejercicio, int numero, String nombre, Set<Solicitud> solicituds, Set<MovCuenta> movCuentas, Set<PlantillaParam> plantillaParams, Set<PlantillaDet> plantillaDets, Set<Asiento> asientos) {
       this.ejercicio = ejercicio;
       this.numero = numero;
       this.nombre = nombre;
       this.solicituds = solicituds;
       this.movCuentas = movCuentas;
       this.plantillaParams = plantillaParams;
       this.plantillaDets = plantillaDets;
       this.asientos = asientos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Ejercicio getEjercicio() {
        return this.ejercicio;
    }
    
    public void setEjercicio(Ejercicio ejercicio) {
        this.ejercicio = ejercicio;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Solicitud> getSolicituds() {
        return this.solicituds;
    }
    
    public void setSolicituds(Set<Solicitud> solicituds) {
        this.solicituds = solicituds;
    }
    public Set<MovCuenta> getMovCuentas() {
        return this.movCuentas;
    }
    
    public void setMovCuentas(Set<MovCuenta> movCuentas) {
        this.movCuentas = movCuentas;
    }
    public Set<PlantillaParam> getPlantillaParams() {
        return this.plantillaParams;
    }
    
    public void setPlantillaParams(Set<PlantillaParam> plantillaParams) {
        this.plantillaParams = plantillaParams;
    }
    public Set<PlantillaDet> getPlantillaDets() {
        return this.plantillaDets;
    }
    
    public void setPlantillaDets(Set<PlantillaDet> plantillaDets) {
        this.plantillaDets = plantillaDets;
    }
    public Set<Asiento> getAsientos() {
        return this.asientos;
    }
    
    public void setAsientos(Set<Asiento> asientos) {
        this.asientos = asientos;
    }




}


