package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1



/**
 * PlantillaDet generated by hbm2java
 */
public class PlantillaDet  implements java.io.Serializable {


     private Integer id;
     private Cuenta cuenta;
     private Plantilla plantilla;
     private char dc;
     private String formula;

    public PlantillaDet() {
    }

	
    public PlantillaDet(Cuenta cuenta, Plantilla plantilla, char dc) {
        this.cuenta = cuenta;
        this.plantilla = plantilla;
        this.dc = dc;
    }
    public PlantillaDet(Cuenta cuenta, Plantilla plantilla, char dc, String formula) {
       this.cuenta = cuenta;
       this.plantilla = plantilla;
       this.dc = dc;
       this.formula = formula;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }
    public Plantilla getPlantilla() {
        return this.plantilla;
    }
    
    public void setPlantilla(Plantilla plantilla) {
        this.plantilla = plantilla;
    }
    public char getDc() {
        return this.dc;
    }
    
    public void setDc(char dc) {
        this.dc = dc;
    }
    public String getFormula() {
        return this.formula;
    }
    
    public void setFormula(String formula) {
        this.formula = formula;
    }




}


