package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ReciboRetencion generated by hbm2java
 */
public class ReciboRetencion  implements java.io.Serializable {


     private Integer id;
     private Recibo recibo;
     private SubcategoriaRetencion subcategoriaRetencion;
     private BigDecimal valorRetencion;

    public ReciboRetencion() {
    }

    public ReciboRetencion(Recibo recibo, SubcategoriaRetencion subcategoriaRetencion, BigDecimal valorRetencion) {
       this.recibo = recibo;
       this.subcategoriaRetencion = subcategoriaRetencion;
       this.valorRetencion = valorRetencion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Recibo getRecibo() {
        return this.recibo;
    }
    
    public void setRecibo(Recibo recibo) {
        this.recibo = recibo;
    }
    public SubcategoriaRetencion getSubcategoriaRetencion() {
        return this.subcategoriaRetencion;
    }
    
    public void setSubcategoriaRetencion(SubcategoriaRetencion subcategoriaRetencion) {
        this.subcategoriaRetencion = subcategoriaRetencion;
    }
    public BigDecimal getValorRetencion() {
        return this.valorRetencion;
    }
    
    public void setValorRetencion(BigDecimal valorRetencion) {
        this.valorRetencion = valorRetencion;
    }




}


