package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Recibo generated by hbm2java
 */
public class Recibo  implements java.io.Serializable {


     private Integer id;
     private CuentaFondos cuentaFondos;
     private Empresa empresa;
     private FormaPago formaPago;
     private Date fecCarga;
     private Date fecMov;
     private int idUsuario;
     private int idBeneficiario;
     private String numCheque;
     private BigDecimal valor;
     private BigDecimal valorRetencion;
     private BigDecimal valorTotal;
     private Integer idAsiento;
     private String observaciones;
     private Set<ReciboRetencion> reciboRetencions = new HashSet<ReciboRetencion>(0);
     private Set<ReciboSol> reciboSols = new HashSet<ReciboSol>(0);

    public Recibo() {
    }

	
    public Recibo(CuentaFondos cuentaFondos, Empresa empresa, FormaPago formaPago, Date fecCarga, Date fecMov, int idUsuario, int idBeneficiario, BigDecimal valor, BigDecimal valorRetencion, BigDecimal valorTotal) {
        this.cuentaFondos = cuentaFondos;
        this.empresa = empresa;
        this.formaPago = formaPago;
        this.fecCarga = fecCarga;
        this.fecMov = fecMov;
        this.idUsuario = idUsuario;
        this.idBeneficiario = idBeneficiario;
        this.valor = valor;
        this.valorRetencion = valorRetencion;
        this.valorTotal = valorTotal;
    }
    public Recibo(CuentaFondos cuentaFondos, Empresa empresa, FormaPago formaPago, Date fecCarga, Date fecMov, int idUsuario, int idBeneficiario, String numCheque, BigDecimal valor, BigDecimal valorRetencion, BigDecimal valorTotal, Integer idAsiento, String observaciones, Set<ReciboRetencion> reciboRetencions, Set<ReciboSol> reciboSols) {
       this.cuentaFondos = cuentaFondos;
       this.empresa = empresa;
       this.formaPago = formaPago;
       this.fecCarga = fecCarga;
       this.fecMov = fecMov;
       this.idUsuario = idUsuario;
       this.idBeneficiario = idBeneficiario;
       this.numCheque = numCheque;
       this.valor = valor;
       this.valorRetencion = valorRetencion;
       this.valorTotal = valorTotal;
       this.idAsiento = idAsiento;
       this.observaciones = observaciones;
       this.reciboRetencions = reciboRetencions;
       this.reciboSols = reciboSols;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CuentaFondos getCuentaFondos() {
        return this.cuentaFondos;
    }
    
    public void setCuentaFondos(CuentaFondos cuentaFondos) {
        this.cuentaFondos = cuentaFondos;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public FormaPago getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(FormaPago formaPago) {
        this.formaPago = formaPago;
    }
    public Date getFecCarga() {
        return this.fecCarga;
    }
    
    public void setFecCarga(Date fecCarga) {
        this.fecCarga = fecCarga;
    }
    public Date getFecMov() {
        return this.fecMov;
    }
    
    public void setFecMov(Date fecMov) {
        this.fecMov = fecMov;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public int getIdBeneficiario() {
        return this.idBeneficiario;
    }
    
    public void setIdBeneficiario(int idBeneficiario) {
        this.idBeneficiario = idBeneficiario;
    }
    public String getNumCheque() {
        return this.numCheque;
    }
    
    public void setNumCheque(String numCheque) {
        this.numCheque = numCheque;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public BigDecimal getValorRetencion() {
        return this.valorRetencion;
    }
    
    public void setValorRetencion(BigDecimal valorRetencion) {
        this.valorRetencion = valorRetencion;
    }
    public BigDecimal getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(BigDecimal valorTotal) {
        this.valorTotal = valorTotal;
    }
    public Integer getIdAsiento() {
        return this.idAsiento;
    }
    
    public void setIdAsiento(Integer idAsiento) {
        this.idAsiento = idAsiento;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set<ReciboRetencion> getReciboRetencions() {
        return this.reciboRetencions;
    }
    
    public void setReciboRetencions(Set<ReciboRetencion> reciboRetencions) {
        this.reciboRetencions = reciboRetencions;
    }
    public Set<ReciboSol> getReciboSols() {
        return this.reciboSols;
    }
    
    public void setReciboSols(Set<ReciboSol> reciboSols) {
        this.reciboSols = reciboSols;
    }




}


