package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Solicitud generated by hbm2java
 */
public class Solicitud  implements java.io.Serializable {


     private Integer id;
     private Asiento asiento;
     private Empresa empresa;
     private Plantilla plantilla;
     private Date fecCarga;
     private Date fecMov;
     private int idUsuario;
     private int idBeneficiario;
     private int tipoComprobante;
     private String numPuntoVenta;
     private String numComprobante;
     private Integer tipoFactura;
     private int tipoIva;
     private int moneda;
     private BigDecimal valorGravado;
     private BigDecimal valorNoGravado;
     private BigDecimal valorIva;
     private BigDecimal valorPercepcion;
     private BigDecimal valorTotal;
     private char estado;
     private Integer idUsuarioAprob;
     private Date fecProc;
     private String observaciones;
     private Set<SolicitudPercepcion> solicitudPercepcions = new HashSet<SolicitudPercepcion>(0);
     private Set<SolicitudIva> solicitudIvas = new HashSet<SolicitudIva>(0);
     private Set<ReciboSol> reciboSols = new HashSet<ReciboSol>(0);

    public Solicitud() {
    }

	
    public Solicitud(Empresa empresa, Plantilla plantilla, Date fecCarga, Date fecMov, int idUsuario, int idBeneficiario, int tipoComprobante, int tipoIva, int moneda, BigDecimal valorGravado, BigDecimal valorNoGravado, BigDecimal valorIva, BigDecimal valorPercepcion, BigDecimal valorTotal, char estado) {
        this.empresa = empresa;
        this.plantilla = plantilla;
        this.fecCarga = fecCarga;
        this.fecMov = fecMov;
        this.idUsuario = idUsuario;
        this.idBeneficiario = idBeneficiario;
        this.tipoComprobante = tipoComprobante;
        this.tipoIva = tipoIva;
        this.moneda = moneda;
        this.valorGravado = valorGravado;
        this.valorNoGravado = valorNoGravado;
        this.valorIva = valorIva;
        this.valorPercepcion = valorPercepcion;
        this.valorTotal = valorTotal;
        this.estado = estado;
    }
    public Solicitud(Asiento asiento, Empresa empresa, Plantilla plantilla, Date fecCarga, Date fecMov, int idUsuario, int idBeneficiario, int tipoComprobante, String numPuntoVenta, String numComprobante, Integer tipoFactura, int tipoIva, int moneda, BigDecimal valorGravado, BigDecimal valorNoGravado, BigDecimal valorIva, BigDecimal valorPercepcion, BigDecimal valorTotal, char estado, Integer idUsuarioAprob, Date fecProc, String observaciones, Set<SolicitudPercepcion> solicitudPercepcions, Set<SolicitudIva> solicitudIvas, Set<ReciboSol> reciboSols) {
       this.asiento = asiento;
       this.empresa = empresa;
       this.plantilla = plantilla;
       this.fecCarga = fecCarga;
       this.fecMov = fecMov;
       this.idUsuario = idUsuario;
       this.idBeneficiario = idBeneficiario;
       this.tipoComprobante = tipoComprobante;
       this.numPuntoVenta = numPuntoVenta;
       this.numComprobante = numComprobante;
       this.tipoFactura = tipoFactura;
       this.tipoIva = tipoIva;
       this.moneda = moneda;
       this.valorGravado = valorGravado;
       this.valorNoGravado = valorNoGravado;
       this.valorIva = valorIva;
       this.valorPercepcion = valorPercepcion;
       this.valorTotal = valorTotal;
       this.estado = estado;
       this.idUsuarioAprob = idUsuarioAprob;
       this.fecProc = fecProc;
       this.observaciones = observaciones;
       this.solicitudPercepcions = solicitudPercepcions;
       this.solicitudIvas = solicitudIvas;
       this.reciboSols = reciboSols;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Asiento getAsiento() {
        return this.asiento;
    }
    
    public void setAsiento(Asiento asiento) {
        this.asiento = asiento;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Plantilla getPlantilla() {
        return this.plantilla;
    }
    
    public void setPlantilla(Plantilla plantilla) {
        this.plantilla = plantilla;
    }
    public Date getFecCarga() {
        return this.fecCarga;
    }
    
    public void setFecCarga(Date fecCarga) {
        this.fecCarga = fecCarga;
    }
    public Date getFecMov() {
        return this.fecMov;
    }
    
    public void setFecMov(Date fecMov) {
        this.fecMov = fecMov;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public int getIdBeneficiario() {
        return this.idBeneficiario;
    }
    
    public void setIdBeneficiario(int idBeneficiario) {
        this.idBeneficiario = idBeneficiario;
    }
    public int getTipoComprobante() {
        return this.tipoComprobante;
    }
    
    public void setTipoComprobante(int tipoComprobante) {
        this.tipoComprobante = tipoComprobante;
    }
    public String getNumPuntoVenta() {
        return this.numPuntoVenta;
    }
    
    public void setNumPuntoVenta(String numPuntoVenta) {
        this.numPuntoVenta = numPuntoVenta;
    }
    public String getNumComprobante() {
        return this.numComprobante;
    }
    
    public void setNumComprobante(String numComprobante) {
        this.numComprobante = numComprobante;
    }
    public Integer getTipoFactura() {
        return this.tipoFactura;
    }
    
    public void setTipoFactura(Integer tipoFactura) {
        this.tipoFactura = tipoFactura;
    }
    public int getTipoIva() {
        return this.tipoIva;
    }
    
    public void setTipoIva(int tipoIva) {
        this.tipoIva = tipoIva;
    }
    public int getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(int moneda) {
        this.moneda = moneda;
    }
    public BigDecimal getValorGravado() {
        return this.valorGravado;
    }
    
    public void setValorGravado(BigDecimal valorGravado) {
        this.valorGravado = valorGravado;
    }
    public BigDecimal getValorNoGravado() {
        return this.valorNoGravado;
    }
    
    public void setValorNoGravado(BigDecimal valorNoGravado) {
        this.valorNoGravado = valorNoGravado;
    }
    public BigDecimal getValorIva() {
        return this.valorIva;
    }
    
    public void setValorIva(BigDecimal valorIva) {
        this.valorIva = valorIva;
    }
    public BigDecimal getValorPercepcion() {
        return this.valorPercepcion;
    }
    
    public void setValorPercepcion(BigDecimal valorPercepcion) {
        this.valorPercepcion = valorPercepcion;
    }
    public BigDecimal getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(BigDecimal valorTotal) {
        this.valorTotal = valorTotal;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public Integer getIdUsuarioAprob() {
        return this.idUsuarioAprob;
    }
    
    public void setIdUsuarioAprob(Integer idUsuarioAprob) {
        this.idUsuarioAprob = idUsuarioAprob;
    }
    public Date getFecProc() {
        return this.fecProc;
    }
    
    public void setFecProc(Date fecProc) {
        this.fecProc = fecProc;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set<SolicitudPercepcion> getSolicitudPercepcions() {
        return this.solicitudPercepcions;
    }
    
    public void setSolicitudPercepcions(Set<SolicitudPercepcion> solicitudPercepcions) {
        this.solicitudPercepcions = solicitudPercepcions;
    }
    public Set<SolicitudIva> getSolicitudIvas() {
        return this.solicitudIvas;
    }
    
    public void setSolicitudIvas(Set<SolicitudIva> solicitudIvas) {
        this.solicitudIvas = solicitudIvas;
    }
    public Set<ReciboSol> getReciboSols() {
        return this.reciboSols;
    }
    
    public void setReciboSols(Set<ReciboSol> reciboSols) {
        this.reciboSols = reciboSols;
    }




}


