package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * SolicitudPercepcion generated by hbm2java
 */
public class SolicitudPercepcion  implements java.io.Serializable {


     private Integer id;
     private Solicitud solicitud;
     private SubcategoriaPercepcion subcategoriaPercepcion;
     private BigDecimal valorPercepcion;

    public SolicitudPercepcion() {
    }

    public SolicitudPercepcion(Solicitud solicitud, SubcategoriaPercepcion subcategoriaPercepcion, BigDecimal valorPercepcion) {
       this.solicitud = solicitud;
       this.subcategoriaPercepcion = subcategoriaPercepcion;
       this.valorPercepcion = valorPercepcion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }
    public SubcategoriaPercepcion getSubcategoriaPercepcion() {
        return this.subcategoriaPercepcion;
    }
    
    public void setSubcategoriaPercepcion(SubcategoriaPercepcion subcategoriaPercepcion) {
        this.subcategoriaPercepcion = subcategoriaPercepcion;
    }
    public BigDecimal getValorPercepcion() {
        return this.valorPercepcion;
    }
    
    public void setValorPercepcion(BigDecimal valorPercepcion) {
        this.valorPercepcion = valorPercepcion;
    }




}


