package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * SolicitudIva generated by hbm2java
 */
public class SolicitudIva  implements java.io.Serializable {


     private Integer id;
     private Iva iva;
     private Solicitud solicitud;
     private BigDecimal valorGravado;
     private BigDecimal porcIva;
     private BigDecimal valorIva;

    public SolicitudIva() {
    }

    public SolicitudIva(Iva iva, Solicitud solicitud, BigDecimal valorGravado, BigDecimal porcIva, BigDecimal valorIva) {
       this.iva = iva;
       this.solicitud = solicitud;
       this.valorGravado = valorGravado;
       this.porcIva = porcIva;
       this.valorIva = valorIva;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Iva getIva() {
        return this.iva;
    }
    
    public void setIva(Iva iva) {
        this.iva = iva;
    }
    public Solicitud getSolicitud() {
        return this.solicitud;
    }
    
    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }
    public BigDecimal getValorGravado() {
        return this.valorGravado;
    }
    
    public void setValorGravado(BigDecimal valorGravado) {
        this.valorGravado = valorGravado;
    }
    public BigDecimal getPorcIva() {
        return this.porcIva;
    }
    
    public void setPorcIva(BigDecimal porcIva) {
        this.porcIva = porcIva;
    }
    public BigDecimal getValorIva() {
        return this.valorIva;
    }
    
    public void setValorIva(BigDecimal valorIva) {
        this.valorIva = valorIva;
    }




}


