package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SubcategoriaRetencion generated by hbm2java
 */
public class SubcategoriaRetencion  implements java.io.Serializable {


     private Integer id;
     private CategoriaRetencion categoriaRetencion;
     private String nombre;
     private String cuentaNumero;
     private Set<ReciboRetencion> reciboRetencions = new HashSet<ReciboRetencion>(0);
     private Set<MovCuentaRet> movCuentaRets = new HashSet<MovCuentaRet>(0);

    public SubcategoriaRetencion() {
    }

	
    public SubcategoriaRetencion(CategoriaRetencion categoriaRetencion, String nombre) {
        this.categoriaRetencion = categoriaRetencion;
        this.nombre = nombre;
    }
    public SubcategoriaRetencion(CategoriaRetencion categoriaRetencion, String nombre, String cuentaNumero, Set<ReciboRetencion> reciboRetencions, Set<MovCuentaRet> movCuentaRets) {
       this.categoriaRetencion = categoriaRetencion;
       this.nombre = nombre;
       this.cuentaNumero = cuentaNumero;
       this.reciboRetencions = reciboRetencions;
       this.movCuentaRets = movCuentaRets;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CategoriaRetencion getCategoriaRetencion() {
        return this.categoriaRetencion;
    }
    
    public void setCategoriaRetencion(CategoriaRetencion categoriaRetencion) {
        this.categoriaRetencion = categoriaRetencion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCuentaNumero() {
        return this.cuentaNumero;
    }
    
    public void setCuentaNumero(String cuentaNumero) {
        this.cuentaNumero = cuentaNumero;
    }
    public Set<ReciboRetencion> getReciboRetencions() {
        return this.reciboRetencions;
    }
    
    public void setReciboRetencions(Set<ReciboRetencion> reciboRetencions) {
        this.reciboRetencions = reciboRetencions;
    }
    public Set<MovCuentaRet> getMovCuentaRets() {
        return this.movCuentaRets;
    }
    
    public void setMovCuentaRets(Set<MovCuentaRet> movCuentaRets) {
        this.movCuentaRets = movCuentaRets;
    }




}


