package entidades;
// Generated 13 nov. 2021 10:48:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SubcategoriaPercepcion generated by hbm2java
 */
public class SubcategoriaPercepcion  implements java.io.Serializable {


     private Integer id;
     private CategoriaPercepcion categoriaPercepcion;
     private String nombre;
     private String cuentaNumero;
     private Set<SolicitudPercepcion> solicitudPercepcions = new HashSet<SolicitudPercepcion>(0);

    public SubcategoriaPercepcion() {
    }

	
    public SubcategoriaPercepcion(CategoriaPercepcion categoriaPercepcion, String nombre) {
        this.categoriaPercepcion = categoriaPercepcion;
        this.nombre = nombre;
    }
    public SubcategoriaPercepcion(CategoriaPercepcion categoriaPercepcion, String nombre, String cuentaNumero, Set<SolicitudPercepcion> solicitudPercepcions) {
       this.categoriaPercepcion = categoriaPercepcion;
       this.nombre = nombre;
       this.cuentaNumero = cuentaNumero;
       this.solicitudPercepcions = solicitudPercepcions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CategoriaPercepcion getCategoriaPercepcion() {
        return this.categoriaPercepcion;
    }
    
    public void setCategoriaPercepcion(CategoriaPercepcion categoriaPercepcion) {
        this.categoriaPercepcion = categoriaPercepcion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCuentaNumero() {
        return this.cuentaNumero;
    }
    
    public void setCuentaNumero(String cuentaNumero) {
        this.cuentaNumero = cuentaNumero;
    }
    public Set<SolicitudPercepcion> getSolicitudPercepcions() {
        return this.solicitudPercepcions;
    }
    
    public void setSolicitudPercepcions(Set<SolicitudPercepcion> solicitudPercepcions) {
        this.solicitudPercepcions = solicitudPercepcions;
    }




}


